#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
eval $(dircolors ~/.dircolors/dircolors.256dark)

# Customize to your needs...
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
